package com.georgeconsulting.expenseReport;



import java.awt.*;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.awt.event.*;
//import javax.swing.*;

public class MainFrame extends javax.swing.JFrame {

    public DBConnect conn;
    public Login newLogin;
    public Employee currentUser;
    public static String temp;
    public String usernameInput;
    public String passwordInput;
    public TravelExpenseReport expReport;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws SQLException {
        conn = new DBConnect();
        newLogin = new Login();
        expReport = new TravelExpenseReport();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("expenseReport?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        chargeToQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM ChargeTo c");
        chargeToList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : chargeToQuery.getResultList();
        newRequestConfirmDialog = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        newReqConfirmButton = new javax.swing.JButton();
        newReqBackButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        userTabPanel = new javax.swing.JTabbedPane();
        basicTabPanel = new javax.swing.JPanel();
        basicMenuPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        newRequestPanel = new javax.swing.JPanel();
        submittedByLabel = new javax.swing.JLabel();
        chargeToLabel = new javax.swing.JLabel();
        airTransLabel = new javax.swing.JLabel();
        gndTransLabel = new javax.swing.JLabel();
        lodgeLabel = new javax.swing.JLabel();
        perdiemLabel = new javax.swing.JLabel();
        otherExpLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submittedByField = new javax.swing.JTextField();
        estTotalLabel = new javax.swing.JLabel();
        newSubmitButton = new javax.swing.JButton();
        newResetButton = new javax.swing.JButton();
        airTransField = new javax.swing.JFormattedTextField();
        gndTransField = new javax.swing.JFormattedTextField();
        lodgeField = new javax.swing.JFormattedTextField();
        perdiemField = new javax.swing.JFormattedTextField();
        otherExpField = new javax.swing.JFormattedTextField();
        estTotalField = new javax.swing.JFormattedTextField();
        submitDateField = new javax.swing.JTextField();
        chargeToDropDown = new javax.swing.JComboBox();
        editRequestPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        deleteRequestPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        viewPendButton = new javax.swing.JButton();
        viewApproveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        viewCompleteButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        managerTabPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        masterTabPanel = new javax.swing.JPanel();
        logoutTabPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();

        newRequestConfirmDialog.setAlwaysOnTop(true);
        newRequestConfirmDialog.setBounds(new java.awt.Rectangle(0, 22, 600, 400));

        jLabel8.setText("Confirm Submission");

        newReqConfirmButton.setText("Submit");
        newReqConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newReqConfirmButtonActionPerformed(evt);
            }
        });

        newReqBackButton.setText("Back");
        newReqBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newReqBackButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout newRequestConfirmDialogLayout = new org.jdesktop.layout.GroupLayout(newRequestConfirmDialog.getContentPane());
        newRequestConfirmDialog.getContentPane().setLayout(newRequestConfirmDialogLayout);
        newRequestConfirmDialogLayout.setHorizontalGroup(
            newRequestConfirmDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(newRequestConfirmDialogLayout.createSequentialGroup()
                .add(newRequestConfirmDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(newRequestConfirmDialogLayout.createSequentialGroup()
                        .add(229, 229, 229)
                        .add(jLabel8))
                    .add(newRequestConfirmDialogLayout.createSequentialGroup()
                        .add(169, 169, 169)
                        .add(newReqConfirmButton)
                        .add(66, 66, 66)
                        .add(newReqBackButton)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        newRequestConfirmDialogLayout.setVerticalGroup(
            newRequestConfirmDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(newRequestConfirmDialogLayout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jLabel8)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 169, Short.MAX_VALUE)
                .add(newRequestConfirmDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newReqConfirmButton)
                    .add(newReqBackButton))
                .add(158, 158, 158))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());

        loginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Log In Panel"));

        loginButton.setText("Log In");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonPressed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        warningLabel.setForeground(java.awt.Color.red);
        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        org.jdesktop.layout.GroupLayout loginPanelLayout = new org.jdesktop.layout.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(loginPanelLayout.createSequentialGroup()
                .add(285, 285, 285)
                .add(loginPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(loginPanelLayout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(loginPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(loginPanelLayout.createSequentialGroup()
                                .add(loginPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel1)
                                    .add(jLabel2))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(loginPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(usernameField)
                                    .add(passwordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(loginPanelLayout.createSequentialGroup()
                                .add(3, 3, 3)
                                .add(loginButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(exitButton))))
                    .add(warningLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 281, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(loginPanelLayout.createSequentialGroup()
                .add(65, 65, 65)
                .add(warningLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(loginPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(usernameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(loginPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(passwordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(loginPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(loginButton)
                    .add(exitButton))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        mainPanel.add(loginPanel, "card2");

        basicMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        basicMenuPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Home Page");

        org.jdesktop.layout.GroupLayout homePanelLayout = new org.jdesktop.layout.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(homePanelLayout.createSequentialGroup()
                .add(267, 267, 267)
                .add(jLabel7)
                .addContainerGap(362, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(homePanelLayout.createSequentialGroup()
                .add(190, 190, 190)
                .add(jLabel7)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        basicMenuPanel.add(homePanel, "card5");

        newRequestPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        submittedByLabel.setText("Submitted By:");

        chargeToLabel.setText("Charge To:");

        airTransLabel.setText("Air Transportation:");

        gndTransLabel.setText("Ground Transportation:");

        lodgeLabel.setText("Lodging:");

        perdiemLabel.setText("Per Diem:");

        otherExpLabel.setText("Other:");

        jLabel3.setText("Submission Date:");

        submittedByField.setEditable(false);

        estTotalLabel.setText("Total:");

        newSubmitButton.setText("Submit");
        newSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSubmitButtonActionPerformed(evt);
            }
        });

        newResetButton.setText("Reset");
        newResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newResetButtonActionPerformed(evt);
            }
        });

        airTransField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(¤#,##0.00)"))));
        airTransField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                airTransFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                airTransFieldFocusLost(evt);
            }
        });

        gndTransField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(¤#,##0.00)"))));
        gndTransField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gndTransFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gndTransFieldFocusLost(evt);
            }
        });

        lodgeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(¤#,##0.00)"))));
        lodgeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lodgeFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lodgeFieldFocusLost(evt);
            }
        });

        perdiemField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(¤#,##0.00)"))));
        perdiemField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                perdiemFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                perdiemFieldFocusLost(evt);
            }
        });

        otherExpField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(¤#,##0.00)"))));
        otherExpField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                otherExpFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                otherExpFieldFocusLost(evt);
            }
        });

        estTotalField.setEditable(false);
        estTotalField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(¤#,##0.00)"))));

        submitDateField.setEditable(false);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, chargeToList, chargeToDropDown);
        bindingGroup.addBinding(jComboBoxBinding);

        org.jdesktop.layout.GroupLayout newRequestPanelLayout = new org.jdesktop.layout.GroupLayout(newRequestPanel);
        newRequestPanel.setLayout(newRequestPanelLayout);
        newRequestPanelLayout.setHorizontalGroup(
            newRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, newRequestPanelLayout.createSequentialGroup()
                .add(59, 59, 59)
                .add(newRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel3)
                    .add(submittedByField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .add(chargeToLabel)
                    .add(submittedByLabel)
                    .add(newSubmitButton)
                    .add(newResetButton)
                    .add(submitDateField)
                    .add(chargeToDropDown, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 139, Short.MAX_VALUE)
                .add(newRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(estTotalLabel)
                    .add(airTransLabel)
                    .add(lodgeLabel)
                    .add(perdiemLabel)
                    .add(otherExpLabel)
                    .add(lodgeField)
                    .add(gndTransField)
                    .add(airTransField)
                    .add(gndTransLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(perdiemField)
                    .add(otherExpField)
                    .add(estTotalField))
                .add(154, 154, 154))
        );
        newRequestPanelLayout.setVerticalGroup(
            newRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(newRequestPanelLayout.createSequentialGroup()
                .add(34, 34, 34)
                .add(newRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(newRequestPanelLayout.createSequentialGroup()
                        .add(airTransLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(airTransField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(gndTransLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(newRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(gndTransField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(submitDateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(lodgeLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lodgeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(perdiemLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(perdiemField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(newRequestPanelLayout.createSequentialGroup()
                        .add(submittedByLabel)
                        .add(newRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(newRequestPanelLayout.createSequentialGroup()
                                .add(134, 134, 134)
                                .add(chargeToLabel))
                            .add(newRequestPanelLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(submittedByField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel3)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chargeToDropDown, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(12, 12, 12)
                .add(newRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(otherExpLabel)
                    .add(newSubmitButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(newRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(newResetButton)
                    .add(otherExpField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(estTotalLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(estTotalField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        basicMenuPanel.add(newRequestPanel, "card2");

        editRequestPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Edit Request");

        org.jdesktop.layout.GroupLayout editRequestPanelLayout = new org.jdesktop.layout.GroupLayout(editRequestPanel);
        editRequestPanel.setLayout(editRequestPanelLayout);
        editRequestPanelLayout.setHorizontalGroup(
            editRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(editRequestPanelLayout.createSequentialGroup()
                .add(290, 290, 290)
                .add(jLabel5)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        editRequestPanelLayout.setVerticalGroup(
            editRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(editRequestPanelLayout.createSequentialGroup()
                .add(174, 174, 174)
                .add(jLabel5)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        basicMenuPanel.add(editRequestPanel, "card3");

        deleteRequestPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Delete Request");

        org.jdesktop.layout.GroupLayout deleteRequestPanelLayout = new org.jdesktop.layout.GroupLayout(deleteRequestPanel);
        deleteRequestPanel.setLayout(deleteRequestPanelLayout);
        deleteRequestPanelLayout.setHorizontalGroup(
            deleteRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(deleteRequestPanelLayout.createSequentialGroup()
                .add(327, 327, 327)
                .add(jLabel4)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        deleteRequestPanelLayout.setVerticalGroup(
            deleteRequestPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(deleteRequestPanelLayout.createSequentialGroup()
                .add(180, 180, 180)
                .add(jLabel4)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        basicMenuPanel.add(deleteRequestPanel, "card4");

        viewPendButton.setText("View Pending");

        viewApproveButton.setText("View Approved");

        editButton.setText("Edit Request");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        newButton.setText("New Request");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Request");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        viewCompleteButton.setText("View Completed");

        jLabel6.setText("Welcome,");

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout basicTabPanelLayout = new org.jdesktop.layout.GroupLayout(basicTabPanel);
        basicTabPanel.setLayout(basicTabPanelLayout);
        basicTabPanelLayout.setHorizontalGroup(
            basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(basicTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(userNameLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(newButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(editButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(deleteButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(viewPendButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(viewApproveButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(viewCompleteButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .add(jLabel6))
                    .add(homeButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(718, Short.MAX_VALUE))
            .add(basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(basicTabPanelLayout.createSequentialGroup()
                    .add(177, 177, 177)
                    .add(basicMenuPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        basicTabPanelLayout.setVerticalGroup(
            basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(basicTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(userNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(homeButton)
                .add(4, 4, 4)
                .add(newButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(editButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(deleteButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(viewPendButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(viewApproveButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(viewCompleteButton)
                .addContainerGap(182, Short.MAX_VALUE))
            .add(basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(basicTabPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(basicMenuPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        userTabPanel.addTab("Basic User", basicTabPanel);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 702, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 468, Short.MAX_VALUE)
        );

        jButton1.setText("View All Pending");

        jButton2.setText("View All Approved");

        jButton3.setText("View All Completed");

        org.jdesktop.layout.GroupLayout managerTabPanelLayout = new org.jdesktop.layout.GroupLayout(managerTabPanel);
        managerTabPanel.setLayout(managerTabPanelLayout);
        managerTabPanelLayout.setHorizontalGroup(
            managerTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, managerTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(managerTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        managerTabPanelLayout.setVerticalGroup(
            managerTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(managerTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(managerTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(managerTabPanelLayout.createSequentialGroup()
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        userTabPanel.addTab("Manager User", managerTabPanel);

        org.jdesktop.layout.GroupLayout masterTabPanelLayout = new org.jdesktop.layout.GroupLayout(masterTabPanel);
        masterTabPanel.setLayout(masterTabPanelLayout);
        masterTabPanelLayout.setHorizontalGroup(
            masterTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 890, Short.MAX_VALUE)
        );
        masterTabPanelLayout.setVerticalGroup(
            masterTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 484, Short.MAX_VALUE)
        );

        userTabPanel.addTab("Master User", masterTabPanel);

        logoutButton.setText("Logout");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout logoutTabPanelLayout = new org.jdesktop.layout.GroupLayout(logoutTabPanel);
        logoutTabPanel.setLayout(logoutTabPanelLayout);
        logoutTabPanelLayout.setHorizontalGroup(
            logoutTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(logoutTabPanelLayout.createSequentialGroup()
                .add(62, 62, 62)
                .add(logoutButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 758, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        logoutTabPanelLayout.setVerticalGroup(
            logoutTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(logoutTabPanelLayout.createSequentialGroup()
                .add(26, 26, 26)
                .add(logoutButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 412, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        userTabPanel.addTab("Logout", logoutTabPanel);

        mainPanel.add(userTabPanel, "card4");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(mainPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(mainPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonPressed
        usernameInput = usernameField.getText();
        passwordInput = new String(passwordField.getPassword());

        try {
            newLogin.getLogin(this.conn, usernameInput, passwordInput);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        userTabPanel.setSelectedComponent(basicTabPanel);

        CardLayout basicMenuItems = (CardLayout) (basicMenuPanel.getLayout());
        basicMenuItems.show(basicMenuPanel, "card5");

        usernameField.setText("");
        passwordField.setText("");
        
        usernameInput = "";
        passwordInput = "";

        if (newLogin.validUser == true) {
            try {
                currentUser = new Employee(newLogin.userID, conn);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (currentUser.privLevel == 1) {
                userTabPanel.setEnabledAt(1, false);
                userTabPanel.setEnabledAt(2, false);
            }
            if (currentUser.privLevel == 2) {
                userTabPanel.setEnabledAt(2, false);
            }

            userNameLabel.setText(currentUser.firstName + " " + currentUser.lastName);

            CardLayout cl = (CardLayout) (mainPanel.getLayout());
            cl.next(mainPanel);
        }
        else {
            newLogin.validUser = false;
            warningLabel.setText("*** INVALID USERNAME/PASSWORD ***");
        }
    }//GEN-LAST:event_loginButtonPressed

    private void logoutButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonPressed
        CardLayout cl = (CardLayout) (mainPanel.getLayout());
        cl.previous(mainPanel);

        userTabPanel.setEnabledAt(1, true);
        userTabPanel.setEnabledAt(2, true);
        
        warningLabel.setText("");
        newLogin.validUser = false;
    }//GEN-LAST:event_logoutButtonPressed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        try {
            conn.conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        CardLayout basicMenuItems = (CardLayout) (basicMenuPanel.getLayout());
        basicMenuItems.show(basicMenuPanel, "card4");
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void newResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newResetButtonActionPerformed
        airTransField.setValue(0);
        gndTransField.setValue(0);
        lodgeField.setValue(0);
        perdiemField.setValue(0);
        otherExpField.setValue(0);
//        estTotalField.setValue(0);
        
        chargeToDropDown.setSelectedIndex(0);
    }//GEN-LAST:event_newResetButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        CardLayout basicMenuItems = (CardLayout) (basicMenuPanel.getLayout());
        basicMenuItems.show(basicMenuPanel, "card2");
        
        submittedByField.setText(currentUser.firstName + " " + currentUser.lastName);
        
        Date todaysDate = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
        
        submitDateField.setText(ft.format(todaysDate));
        
        airTransField.setValue(0);
        gndTransField.setValue(0);
        lodgeField.setValue(0);
        perdiemField.setValue(0);
        otherExpField.setValue(0);
        estTotalField.setValue(0);
        
        expReport.empID = currentUser.empID;
        expReport.requestDate = ft.format(todaysDate);
    }//GEN-LAST:event_newButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        CardLayout basicMenuItems = (CardLayout) (basicMenuPanel.getLayout());
        basicMenuItems.show(basicMenuPanel, "card3");
    }//GEN-LAST:event_editButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        CardLayout basicMenuItems = (CardLayout) (basicMenuPanel.getLayout());
        basicMenuItems.show(basicMenuPanel, "card5");
    }//GEN-LAST:event_homeButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        loginButtonPressed(evt);
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void newSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSubmitButtonActionPerformed
        expReport.estTotal = Float.parseFloat(estTotalField.getText());
        
        newRequestConfirmDialog.setVisible(true);
    }//GEN-LAST:event_newSubmitButtonActionPerformed

    private void airTransFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_airTransFieldFocusLost
        temp = airTransField.getText();
        
        if(airTransField.getText().equals("")) {
            airTransField.setText(temp);
        }
        else {
            float air = Float.parseFloat(airTransField.getText());
            float gnd = Float.parseFloat(gndTransField.getText());
            float lodge = Float.parseFloat(lodgeField.getText());
            float pd = Float.parseFloat(perdiemField.getText());
            float other = Float.parseFloat(otherExpField.getText());
        
            estTotalField.setValue(air + gnd + lodge + pd + other);
            
            expReport.estAir = air;
        }
    }//GEN-LAST:event_airTransFieldFocusLost

    private void gndTransFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gndTransFieldFocusLost
        temp = gndTransField.getText();
        
        if(gndTransField.getText().equals("")) {
            gndTransField.setText(temp);
        }
        else {
            float air = Float.parseFloat(airTransField.getText());
            float gnd = Float.parseFloat(gndTransField.getText());
            float lodge = Float.parseFloat(lodgeField.getText());
            float pd = Float.parseFloat(perdiemField.getText());
            float other = Float.parseFloat(otherExpField.getText());
        
            estTotalField.setValue(air + gnd + lodge + pd + other);
            
            expReport.estGnd = gnd;
        }
    }//GEN-LAST:event_gndTransFieldFocusLost

    private void lodgeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lodgeFieldFocusLost
        temp = lodgeField.getText();
        
        if(lodgeField.getText().equals("")) {
            lodgeField.setText(temp);
        }
        else {
            float air = Float.parseFloat(airTransField.getText());
            float gnd = Float.parseFloat(gndTransField.getText());
            float lodge = Float.parseFloat(lodgeField.getText());
            float pd = Float.parseFloat(perdiemField.getText());
            float other = Float.parseFloat(otherExpField.getText());
        
            estTotalField.setValue(air + gnd + lodge + pd + other);
            
            expReport.estLodge = lodge;
        }
    }//GEN-LAST:event_lodgeFieldFocusLost

    private void perdiemFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perdiemFieldFocusLost
        temp = perdiemField.getText();
        
        if(perdiemField.getText().equals("")) {
            perdiemField.setText(temp);
        }
        else {
            float air = Float.parseFloat(airTransField.getText());
            float gnd = Float.parseFloat(gndTransField.getText());
            float lodge = Float.parseFloat(lodgeField.getText());
            float pd = Float.parseFloat(perdiemField.getText());
            float other = Float.parseFloat(otherExpField.getText());
        
            estTotalField.setValue(air + gnd + lodge + pd + other);
            
            expReport.estPerdiem = pd;
        }
    }//GEN-LAST:event_perdiemFieldFocusLost

    private void otherExpFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otherExpFieldFocusLost
        temp = otherExpField.getText();
        
        if(otherExpField.getText().equals("")) {
            otherExpField.setText(temp);
        }
        else {
            float air = Float.parseFloat(airTransField.getText());
            float gnd = Float.parseFloat(gndTransField.getText());
            float lodge = Float.parseFloat(lodgeField.getText());
            float pd = Float.parseFloat(perdiemField.getText());
            float other = Float.parseFloat(otherExpField.getText());
        
            estTotalField.setValue(air + gnd + lodge + pd + other);
            
            expReport.estOther = other;
        }
    }//GEN-LAST:event_otherExpFieldFocusLost

    private void airTransFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_airTransFieldFocusGained
        airTransField.setText(airTransField.getText());
        airTransField.selectAll();
    }//GEN-LAST:event_airTransFieldFocusGained

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            conn.conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void gndTransFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gndTransFieldFocusGained
        gndTransField.setText(gndTransField.getText());
        gndTransField.selectAll();
    }//GEN-LAST:event_gndTransFieldFocusGained

    private void lodgeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lodgeFieldFocusGained
        lodgeField.setText(lodgeField.getText());
        lodgeField.selectAll();
    }//GEN-LAST:event_lodgeFieldFocusGained

    private void perdiemFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perdiemFieldFocusGained
        perdiemField.setText(perdiemField.getText());
        perdiemField.selectAll();
    }//GEN-LAST:event_perdiemFieldFocusGained

    private void otherExpFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otherExpFieldFocusGained
        otherExpField.setText(otherExpField.getText());
        otherExpField.selectAll();
    }//GEN-LAST:event_otherExpFieldFocusGained

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        logoutButton.setBackground(Color.RED);
        logoutButton.setFont(new Font("Lucinda Grande", Font.PLAIN, 150));
        logoutButton.setText("LOGOUT");
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        logoutButton.setBackground(Color.white);
        logoutButton.setFont(new Font("Lucinda Grande", Font.PLAIN, 13));
        logoutButton.setText("Logout");
    }//GEN-LAST:event_logoutButtonMouseExited

    private void newReqConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newReqConfirmButtonActionPerformed
        System.out.println(expReport.empID);
        System.out.println(expReport.estAir);
        System.out.println(expReport.estGnd);
        System.out.println(expReport.estLodge);
        System.out.println(expReport.estPerdiem);
        System.out.println(expReport.estOther);
        System.out.println(expReport.estTotal);
        System.out.println(expReport.requestDate);
        
//        ArrayList<TravelExpenseReport> input = new ArrayList();
//        
//        System.out.println(input.get(0));
        
//        try {
//            expReport.newEntry(conn, currentUser, input);
//        } catch (SQLException ex) {
//            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }

        
//        newRequestConfirmDialog.dispose();
//        
//        airTransField.setValue(0);
//        gndTransField.setValue(0);
//        lodgeField.setValue(0);
//        perdiemField.setValue(0);
//        otherExpField.setValue(0);
//        
//        chargeToDropDown.setSelectedIndex(0);
//        
//        homeButtonActionPerformed(evt);
    }//GEN-LAST:event_newReqConfirmButtonActionPerformed

    private void newReqBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newReqBackButtonActionPerformed
        newRequestConfirmDialog.dispose();
    }//GEN-LAST:event_newReqBackButtonActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFormattedTextField airTransField;
    public javax.swing.JLabel airTransLabel;
    public javax.swing.JPanel basicMenuPanel;
    public javax.swing.JPanel basicTabPanel;
    public javax.swing.JComboBox chargeToDropDown;
    public javax.swing.JLabel chargeToLabel;
    public java.util.List<com.georgeconsulting.expenseReport.ChargeTo> chargeToList;
    public javax.persistence.Query chargeToQuery;
    public javax.swing.JButton deleteButton;
    public javax.swing.JPanel deleteRequestPanel;
    public javax.swing.JButton editButton;
    public javax.swing.JPanel editRequestPanel;
    public javax.persistence.EntityManager entityManager;
    public javax.swing.JFormattedTextField estTotalField;
    public javax.swing.JLabel estTotalLabel;
    public javax.swing.JButton exitButton;
    public javax.swing.JFormattedTextField gndTransField;
    public javax.swing.JLabel gndTransLabel;
    public javax.swing.JButton homeButton;
    public javax.swing.JPanel homePanel;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JFormattedTextField lodgeField;
    public javax.swing.JLabel lodgeLabel;
    public javax.swing.JButton loginButton;
    public javax.swing.JPanel loginPanel;
    public javax.swing.JButton logoutButton;
    public javax.swing.JPanel logoutTabPanel;
    public javax.swing.JPanel mainPanel;
    public javax.swing.JPanel managerTabPanel;
    public javax.swing.JPanel masterTabPanel;
    public javax.swing.JButton newButton;
    public javax.swing.JButton newReqBackButton;
    public javax.swing.JButton newReqConfirmButton;
    public javax.swing.JDialog newRequestConfirmDialog;
    public javax.swing.JPanel newRequestPanel;
    public javax.swing.JButton newResetButton;
    public javax.swing.JButton newSubmitButton;
    public javax.swing.JFormattedTextField otherExpField;
    public javax.swing.JLabel otherExpLabel;
    public javax.swing.JPasswordField passwordField;
    public javax.swing.JFormattedTextField perdiemField;
    public javax.swing.JLabel perdiemLabel;
    public javax.swing.JTextField submitDateField;
    public javax.swing.JTextField submittedByField;
    public javax.swing.JLabel submittedByLabel;
    public javax.swing.JLabel userNameLabel;
    public javax.swing.JTabbedPane userTabPanel;
    public javax.swing.JTextField usernameField;
    public javax.swing.JButton viewApproveButton;
    public javax.swing.JButton viewCompleteButton;
    public javax.swing.JButton viewPendButton;
    public javax.swing.JLabel warningLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
